[package]
name = "input-device"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
thiserror = "2.0.12"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13.1"
x11rb = "0.13.1"
